// Server-side-only list of valid access codes.
//
// IMPORTANT: this file lives under api/_lib/ (not src/), and Vercel does not
// treat files inside an "_"-prefixed folder as routes/endpoints — so it is
// only ever readable by the serverless function (api/redeem-code.js) that
// imports it, and it is NEVER bundled into the app that ships to the
// browser. That's what makes real one-code-per-person enforcement possible.
//
// To add more codes: add more strings below, in the same format, and
// redeploy. To revoke a code that hasn't been used yet: delete it and
// redeploy (codes already redeemed keep working for whoever redeemed them,
// since that record lives in the Vercel KV store, not here).
export const VALID_ACCESS_CODES = [
  "FATI-23RFR", "FATI-2JSFM", "FATI-2KUAB", "FATI-2SU27", "FATI-2T3MG", "FATI-3DUHJ", "FATI-3SBSN", "FATI-42BBB",
  "FATI-42VMK", "FATI-49534", "FATI-49QJG", "FATI-4FA8T", "FATI-4FGPT", "FATI-4HG2K", "FATI-4J8HJ", "FATI-4W78U",
  "FATI-55XJH", "FATI-5D7Z6", "FATI-5EDQC", "FATI-5GJHP", "FATI-5RMU7", "FATI-5YJNF", "FATI-65RX3", "FATI-66Z97",
  "FATI-68JU8", "FATI-6KYVU", "FATI-6RFAU", "FATI-6WEHM", "FATI-6WZ4E", "FATI-7BKDF", "FATI-7H26M", "FATI-7P7W4",
  "FATI-7XKDH", "FATI-88NHQ", "FATI-89TH8", "FATI-8E4S6", "FATI-8G8PS", "FATI-8GN44", "FATI-8GVET", "FATI-8SFGP",
  "FATI-8YSWX", "FATI-94FQS", "FATI-969JC", "FATI-9B5JE", "FATI-9DP2E", "FATI-9DR45", "FATI-9EBBP", "FATI-9HDET",
  "FATI-9NGZG", "FATI-9PP8Z", "FATI-9SH4X", "FATI-9V7N5", "FATI-A32ST", "FATI-A6Q4P", "FATI-AEDNA", "FATI-AEND4",
  "FATI-AHAZU", "FATI-AJJY8", "FATI-AJM8D", "FATI-AMYFK", "FATI-AP745", "FATI-ASQKE", "FATI-AY6RV", "FATI-B6363",
  "FATI-BU2B4", "FATI-BYQC8", "FATI-BYX94", "FATI-CCQ4D", "FATI-CGFMB", "FATI-CPBAK", "FATI-CSZQH", "FATI-CX732",
  "FATI-CZHFC", "FATI-D89RB", "FATI-DDQCQ", "FATI-DJB3J", "FATI-DK4FV", "FATI-DS38G", "FATI-DVUWK", "FATI-E3GP5",
  "FATI-E49XM", "FATI-E6UMP", "FATI-E7UYC", "FATI-EQ74J", "FATI-ETAT9", "FATI-EZWB4", "FATI-EZXE6", "FATI-FA3FR",
  "FATI-FBGKK", "FATI-FCMCH", "FATI-FDB2E", "FATI-FDE74", "FATI-FFG7S", "FATI-FHHSV", "FATI-FN6AP", "FATI-FR7D4",
  "FATI-G3TBD", "FATI-G79QE", "FATI-G98AR", "FATI-GHGGW", "FATI-GHKHV", "FATI-GHVXG", "FATI-GW8UP", "FATI-GYQKV",
  "FATI-HCBUM", "FATI-HCX36", "FATI-HP6CQ", "FATI-HVT2X", "FATI-HX7HB", "FATI-J8DSW", "FATI-J8WJZ", "FATI-JAPNU",
  "FATI-JETHD", "FATI-JNP9V", "FATI-JNXAR", "FATI-JPE7M", "FATI-JU62P", "FATI-JXKUP", "FATI-JXYXK", "FATI-JZGZ9",
  "FATI-KASXQ", "FATI-KJA27", "FATI-KNANR", "FATI-KR8W6", "FATI-KREQJ", "FATI-KUNP5", "FATI-MEXCT", "FATI-MF82A",
  "FATI-MGKZA", "FATI-MK5A2", "FATI-MQYG3", "FATI-N3CG2", "FATI-NBSBQ", "FATI-ND59R", "FATI-NDHZ6", "FATI-NQJBD",
  "FATI-NZGHH", "FATI-PN68E", "FATI-PPDWB", "FATI-PTNMB", "FATI-PUWCF", "FATI-PWX25", "FATI-Q856A", "FATI-Q898N",
  "FATI-QAWSH", "FATI-QBRN7", "FATI-QJ38D", "FATI-QS4PS", "FATI-QVQXQ", "FATI-QVSSY", "FATI-R58RX", "FATI-RCDMJ",
  "FATI-RF3M3", "FATI-RHH8Y", "FATI-RK3YH", "FATI-RMKZ9", "FATI-RTR8Y", "FATI-RUB3H", "FATI-RV7Q7", "FATI-S7F3Z",
  "FATI-SB939", "FATI-SBWCZ", "FATI-SBX2U", "FATI-SEJT7", "FATI-SFN86", "FATI-SGSAJ", "FATI-SNRY2", "FATI-STTAQ",
  "FATI-T7Q64", "FATI-TRRD6", "FATI-TS434", "FATI-U645J", "FATI-UEA9X", "FATI-UQAMW", "FATI-UT6ZJ", "FATI-UWWYS",
  "FATI-V6YYH", "FATI-VPGVA", "FATI-VWGNE", "FATI-W3C5C", "FATI-W7CWN", "FATI-W8AHR", "FATI-WJB7D", "FATI-WNTBB",
  "FATI-WPMBE", "FATI-WWCEH", "FATI-WYDCT", "FATI-X8EPG", "FATI-XCZHC", "FATI-XD5KU", "FATI-XNNMF", "FATI-Y8ZX2",
  "FATI-Y9M4Y", "FATI-YH6SA", "FATI-YPJK8", "FATI-Z6PM9", "FATI-ZBZQ2", "FATI-ZHTNA", "FATI-ZSG9K", "FATI-ZUMTU",
];
