import {
  FaBookOpen,
  FaBookReader,
  FaBullseye,
  FaCalendarCheck,
  FaChartLine,
  FaCheckSquare,
  FaClipboardList,
  FaClock,
  FaCoffee,
  FaCog,
  FaCommentDots,
  FaFeatherAlt,
  FaGem,
  FaGift,
  FaHeart,
  FaHeartbeat,
  FaHome,
  FaLeaf,
  FaMobileAlt,
  FaMosque,
  FaPlus,
  FaRegClock,
  FaSmile,
  FaSpa,
  FaStar,
  FaTasks,
  FaTrashAlt,
  FaTrophy,
  FaUsers,
  FaWallet,
} from "react-icons/fa";
import { GiBrain, GiMirrorMirror } from "react-icons/gi";

const registry = {
  FaBookOpen,
  FaBookReader,
  FaBullseye,
  FaCalendarCheck,
  FaChartLine,
  FaCheckSquare,
  FaClipboardList,
  FaClock,
  FaCoffee,
  FaCog,
  FaCommentDots,
  FaFeatherAlt,
  FaGem,
  FaGift,
  FaHeart,
  FaHeartbeat,
  FaHome,
  FaLeaf,
  FaMobileAlt,
  FaMosque,
  FaPlus,
  FaRegClock,
  FaSmile,
  FaSpa,
  FaStar,
  FaTasks,
  FaTrashAlt,
  FaTrophy,
  FaUsers,
  FaWallet,
  GiBrain,
  GiMirrorMirror,
};

export default function Icon({ name, className = "", size }) {
  const Cmp = registry[name];
  if (!Cmp) return null;
  return <Cmp className={className} size={size} />;
}
